### ISSUE TITLE
Is this plugin not compatible with Jellyfin version 10.8?

### ISSUE THREAD

**Issue by jyh9521** [danieladov/jellyfin-plugin-themesongs#14]
[2022-02-07 20:24:27.053 +08:00] [INF] [25] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Downloading TV Theme Songs
[2022-02-07 20:24:27.054 +08:00] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/ThemeSongs/DownloadTVShows".
System.MissingMethodException: Method not found: 'System.Guid[] MediaBrowser.Controller.Entities.BaseItem.get_ThemeSongIds()'.
   at Jellyfin.Plugin.ThemeSongs.ThemeSongsManager.DownloadAllThemeSongs()
   at Jellyfin.Plugin.ThemeSongs.Api.ThemeSongsController.DownloadTVThemeSongsRequest()

**Comment by danieladov** [comment]
I've just released a new version for 10.8
