### ISSUE TITLE
"Theme song not in database, or no internet connection"

### ISSUE THREAD

**Issue by Zippy1970** [danieladov/jellyfin-plugin-themesongs#16]
Running version 10.7.7 of Jellyfin and version 10.7.0.2 of the plugin.

The plugin is not downloading theme songs, and the Jellyfin log file shows the above error message.

TVDB plugin is installed and active. All users (including the jellyfin user) on the system (a Raspberry Pi) have write access to the folders where the media is stored. the RPi has a working internet connection.

What else could be wrong?

**Comment by danieladov** [comment]
What are the theme songs you are trying to download?
Does jellyfin have write access to the folders where the tv shows are?

**Comment by Zippy1970** [comment]
Hi, and thank you for your answer!

Yes, Jellyfin has write access to all media folders. Or I think it has since it is able to create metadata folders and files inside the media folders.

The theme songs are (amongst others) Family Guy, Star Trek Next Generation, Wandavision and Star Trek Picard.

**Comment by danieladov** [comment]
That's strange, those songs should be downloaded so it's either a network problem or a permission error.
What version of jellyfin are you using?

**Comment by Zippy1970** [comment]
Version info is in my original post. Running 10.7.7 of jellyfin and 10.7.0.2 of the plugin. It has a working internet connection (it downloads all other metadata just fine) en like I said, all users have rw access to the drive.

It's a network share, BTW, mounted with the **noperm** option.

**Comment by Zippy1970** [comment]
PS: I just checked and jellyfin has write permissions.

**Comment by danieladov** [comment]
Could you try the plugin I've attached? We should get more information with this one

[Jellyfin.Plugin.ThemeSongs.zip](https://github.com/danieladov/jellyfin-plugin-themesongs/files/8383438/Jellyfin.Plugin.ThemeSongs.zip)

**Comment by Zippy1970** [comment]
For one show (The Center Seat) I got: "The remote server returned an error: (404) Not Found."

For all other shows I got: "An exception occurred during a WebClient request."

**Comment by danieladov** [comment]
Could you post an screenshot?

**Comment by Zippy1970** [comment]
From the log file?

**Comment by Zippy1970** [comment]
There is no stacktrace, unless I'm looking at the wrong logfile? This is what's in the logfile:

`[2022-03-30 21:55:16.447 +01:00] [INF] Downloading TV Theme Songs
[2022-03-30 21:55:16.805 +01:00] [INF] "The Center Seat: 55 Years of Star Trek" theme song not in database, or no internet connection
[2022-03-30 21:55:16.805 +01:00] [INF] The remote server returned an error: (404) Not Found.
[2022-03-30 21:55:16.906 +01:00] [INF] "Victorious" theme song not in database, or no internet connection
[2022-03-30 21:55:16.906 +01:00] [INF] An exception occurred during a WebClient request.
[2022-03-30 21:55:17.021 +01:00] [INF] "Family Guy" theme song not in database, or no internet connection
[2022-03-30 21:55:17.022 +01:00] [INF] An exception occurred during a WebClient request.
[2022-03-30 21:55:17.132 +01:00] [INF] "Star Trek: Picard" theme song not in database, or no internet connection
[2022-03-30 21:55:17.133 +01:00] [INF] An exception occurred during a WebClient request.
[2022-03-30 21:55:17.168 +01:00] [INF] "WandaVision" theme song not in database, or no internet connection
[2022-03-30 21:55:17.169 +01:00] [INF] An exception occurred during a WebClient request.
[2022-03-30 21:55:17.335 +01:00] [INF] "Star Trek: The Next Generation" theme song not in database, or no internet connection
[2022-03-30 21:55:17.336 +01:00] [INF] An exception occurred during a WebClient request.
[2022-03-30 21:55:17.445 +01:00] [INF] "The Curse of Oak Island" theme song not in database, or no internet connection
[2022-03-30 21:55:17.445 +01:00] [INF] An exception occurred during a WebClient request.
[2022-03-30 21:55:17.445 +01:00] [INF] Completed
[2022-03-30 21:55:17.446 +01:00] [WRN] Slow HTTP Response from "http://192.168.1.137:8096/ThemeSongs/DownloadTVShows" to "192.168.1.100" in 0:00:01.0074714 with Status Code 204
[2022-03-30 21:55:50.655 +01:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-03-30 21:56:02.656 +01:00] [INF] Lost 1 WebSockets.`

**Comment by Zippy1970** [comment]
Ok, I was looking at the jellyfin log. Here's the info from syslog:

Mar 30 21:55:17 raspberrypi jellyfin[27877]: [21:55:17] [INF] Family Guy theme song not in database, or no internet connection
Mar 30 21:55:17 raspberrypi jellyfin[27877]: [21:55:17] [INF] An exception occurred during a WebClient request.
Mar 30 21:55:17 raspberrypi jellyfin[27877]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
Mar 30 21:55:17 raspberrypi jellyfin[27877]:    at System.Net.WebClient.DownloadFile(String address, String fileName)
Mar 30 21:55:17 raspberrypi jellyfin[27877]:    at Jellyfin.Plugin.ThemeSongs.ThemeSongsManager.DownloadAllThemeSongs()
Mar

**Comment by Zippy1970** [comment]
If I add a TV series library on the local drive, it downloads the theme songs just fine (for the TV series on the local drive) unless there's a space somewhere in the path name. If there's a space in the path name, it either searches for the complete wrong series, or it searches for the right series, but I get the same error as in the subject line.

On the network share, spaces in the path make no difference. I always get the error.

Jellyfin can write to the media folders on the network share just fine since like I said, it saves it's metadata (and images) there.

**Comment by Zippy1970** [comment]
I've been looking at your code and I don't think it's a problem in your code. Something else is at play here. Just can't find what.

**Comment by Zippy1970** [comment]
I've been trying to build the plugin myself but for some reason, the resulting dll is waayyy smaller than the original and when I replace the original dll with mine, the plugin "malfunctions". This is my first time working with dotnet so I'm not sure what I'm doing wrong.

**Comment by danieladov** [comment]
> If I add a TV series library on the local drive, it downloads the theme songs just fine (for the TV series on the local drive) **unless** there's a space somewhere in the path name. If there's a space in the path name, it either searches for the complete wrong series, or it searches for the right series, but I get the same error as in the subject line.
> 
> On the network share, spaces in the path make no difference. I always get the error.
> 
> Jellyfin can write to the media folders on the network share just fine since like I said, it saves it's metadata (and images) there.

That's strange, I do have spaces in some of my series and the songs get download correctly, I still think the problem must be a permission issue.

**Comment by danieladov** [comment]
> I've been trying to build the plugin myself but for some reason, the resulting dll is waayyy smaller than the original and when I replace the original dll with mine, the plugin "malfunctions". This is my first time working with dotnet so I'm not sure what I'm doing wrong.
> 
> The error in syslog when it tries to load the plugin is:
> 
> ` System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

You are compiling the last version, you need to use the 10.7.0.2 version for your server

**Comment by Zippy1970** [comment]
If I try to build 10.7.0.2, I get error that it can't find YouTubeSearch and YoutubeExplode...

Like I said, my first time working with dotnet,

**Comment by danieladov** [comment]
Yeah that's normal, it's because in that version there was a beta feature to download also movie theme songs, you need to place the files I've attached with your dll
[Jellyfin-Plugin-ThemeSongs.zip](https://github.com/danieladov/jellyfin-plugin-themesongs/files/8388691/Jellyfin-Plugin-ThemeSongs.zip)

**Comment by Zippy1970** [comment]
Ok, now it builds fine, but when restarting Jellyfin, it doesn't load the plugin and I get error:

```
[ERR] Failed to load assembly /var/lib/jellyfin/plugins/Theme Songs_10.7.0.2/Jellyfin.Plugin.ThemeSongs.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturnVoid' from assembly 'MediaBrowser.Model, Version=10.7.7.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by Zippy1970** [comment]
Weird, I just noticed it's not targeting net6.0 but netstandard2.1. Is this perhaps the problem?

**Comment by Zippy1970** [comment]
Cool, that works. Gonna do some debugging now. :)

**Comment by Zippy1970** [comment]
The error is indeed a permission problem:

` Access to the path '/mnt/LS-XHL424/TV Series/Star Trek The Next Generation/theme.mp3' is denied`

But that's weird because (the) jellyfin (user) writes to the same path constantly (metadata and images).

**Comment by Zippy1970** [comment]
Yes, but that can be overridden in the settings.

**Comment by Zippy1970** [comment]
Well, I have no idea whats going on. Any user can read/create/delete/modify files on the network share. Even Jellyfin itself. I can even create new users and they have full access as well. But the plugin (more specifically, WebClient) keeps giving the "access denied" error. Since WebClient is decrepated, have you thought about moving 
to HttpClient?

**Comment by Castcore** [comment]
I am getting the same error as well actually and can confirm it is only for my libraries that run on a synology NAS through smb share folders. A local library with a test tv series (Rick and Morty) on it seems to download the theme song successfully.

Here are the logs:

> [20:12:33] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Downloading TV Theme Songs
[20:12:33] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Rick and Morty theme song succesfully downloaded
[20:12:33] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Stranger Things theme song not in database, or no internet connection
[20:12:34] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Boys theme song not in database, or no internet connection
[20:12:34] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Watchmen theme song not in database, or no internet connection
[20:12:34] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Dark theme song not in database, or no internet connection
[20:12:35] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Severance theme song not in database, or no internet connection
[20:12:35] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Ted Lasso theme song not in database, or no internet connection
[20:12:35] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Arcane theme song not in database, or no internet connection
[20:12:35] [INF] [9] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Completed
[20:12:35] [WRN] [9] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://[server_IP]/ThemeSongs/DownloadTVShows to [client_IP] in 0:00:02.4579023 with Status Code 204<

I tested if Jellyfin has write access to the shared library from within the docker container by running:

`docker exec -it jellyfin /bin/bash`
`cd /[synology_nas_share_folder]/'TV Shows'`
`touch testfile.txt`

I then verified that the file was indeed created on my nas. Upon reading that the space in the 'TV Shows' folder may cause the same issue to occur on the local library as mentioned by Zippy1970 I tested the exact same process with the shared folder now called "TV_Shows" and the same Rick and Morty test series. The theme song plugin resulted in "Rick and Morty theme song not in database, or no internet connection".

Not sure how to proceed, perhaps there is a better method for testing the write permissions that I cannot think of?

**Comment by danieladov** [comment]
I'll try to make a new version with more updated libraries, that might fix your problem. I'll let you know when it's ready

**Comment by danieladov** [comment]
Hi! Could you try this version of the plugin? 
[Jellyfin.Plugin.ThemeSongs.dll.zip](https://github.com/danieladov/jellyfin-plugin-themesongs/files/8900451/Jellyfin.Plugin.ThemeSongs.dll.zip)

**Comment by Castcore** [comment]
Unfortunately using your latest file I am receiving an error say that the plugin malfunctioned in the meta.json file.

meta.json
>"category": "", 
"changelog": "", 
"description": "", 
"guid": "e25d0f53-2098-0c13-a4a6-4ee0e0a87ae5", 
"name": "themesong", 
"overview": "", 
"owner": "", 
"targetAbi": "10.7.7.0", 
"timestamp": "0001-01-01T00:00:00.0000000Z", 
"version": "10.7.7.0", 
"status": "Malfunctioned", 
"autoUpdate": false

I couldn't find anything extra in the log files to go off of but the previous dll you attached for Zippy1970 did successfully install  for me but the songs were still not downloaded.
I've also tried to modify, clone, and compile your code from this repo myself and was running into the plugin malfunction problem. What I tried to do was change line 57 of "ThemeSongManager.cs" from
`_logger.LogDebug("Trying to download {seriesName}, {link}", serie.Name, link);`
to
`_logger.LogInformation("Trying to download {seriesName}, {link}, download path is: {themeSongPath}", serie.Name, link, themeSongPath);`
So I could easily see what path it was trying to use in my portainer jellyfin logs, but I couldn't get it to install successfully on my jellyfin server.

**Comment by tony77682** [comment]
hello, I use a jellyfin server Version: 10.9.0 in docker with the plugin theme song Version 10.8.0.1. I have permissions to access the folders. and I also have the error "Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: "xxxx" theme song not in database, or no internet connection"

**Comment by Sledgehamma** [comment]
I face the same issue as OP, but for me its because Jellyfin does not have write access to the TV share. Would it be possible that the themes are saved to the same system path like all the other metadata in case Jellyfin does not have write access?

**Comment by Zippy1970** [comment]
> Hi! Could you try this version of the plugin? [Jellyfin.Plugin.ThemeSongs.dll.zip](https://github.com/danieladov/jellyfin-plugin-themesongs/files/8900451/Jellyfin.Plugin.ThemeSongs.dll.zip)

Sorry, never saw this post until now... :o

I tried it and the first time I ran it, the log file gave me this for every single show:

`ERROR: Access to the path '/mnt/LS-XHL424/TV Series/(tv show)/theme.mp3' is denied.`

But if I check the folders, it created an empty (0 bytes) theme.mp3 file in each of them (so it does have write/create permissions). Running it a second time, the log file either says:

`ERROR: Access to the path '/mnt/LS-XHL424/TV Series/(tv show)/theme.mp3' is denied.`

or

`ERROR: The file '/mnt/LS-XHL424/TV Series/(tv show)/theme.mp3' already exists.`

Which error it gives seems totally random.

**Comment by Zippy1970** [comment]
Sooooo... Any ideas?

**Comment by danieladov** [comment]
I honestly don't know where the problem is, it has to be a permission error. Make sure jellyfin can write to that path

**Comment by Zippy1970** [comment]
Yes, any and all users have complete access to the path. As you can seen, it even creates an empty (0 byte) theme.mp3 file. So it's not a permission problem for **_that_** path.

Is the plugin perhaps downloading the theme song to a different location first (much like how Windows downloads files) then copies it over when the download has finished?

**Comment by Oratorian** [comment]
After inspecting your sourcecode, i found out you are download songs from http://tvthemes.plexapp.com
provided with the tvdbID.

There are show where plex does not store this information in the tvthemes url anymore.

**Comment by JackTheExecuter** [comment]
Jellyfin server: 10.8.9
Theme Songs plugin: 10.8.0.1
Video folder is a mounted share.

First of all, really great idea, i love it!
But i'm facing the same issue:

[2023-01-29 16:20:26.416 +01:00] [INF] Downloading TV Theme Songs
[2023-01-29 16:20:26.432 +01:00] [INF] "Tom und Jerry" theme song not in database, or no internet connection
[2023-01-29 16:20:26.436 +01:00] [INF] "Es war einmal... Der Mensch" theme song not in database, or no internet connection

I made sure that there isn't a permission issue.
The service user has full share and file permissions.
I also copied a series to a local folder /home/XYZ and the same issue occurs.

Regards

**Comment by eomiku** [comment]
I am also experiencing this issue. I also don't believe it is a permissions issue as it occurs randomly. Some new additions to the folder have theme songs downloaded to it, some do not. It seems to be a data base issue

**Comment by Makkoacknowledgesstress** [comment]
I'm actually experiencing the same exact issue, its really really frustrating, tried everything from permissions to redoing the server all over again and I'm still experiencing the same exact conclusion, the plugin just wont work on linux as it did on windows for me.

**Comment by Zippy1970** [comment]
> Is the plugin perhaps downloading the theme song to a different location first (much like how Windows downloads files) then copies it over when the download has finished?

Just repeating the question. :)

**Comment by Cameron-Gregg** [comment]
Hey all, 
I have the same issue and I think I might know what the problem is. GEORESTRICTIONS. 

So when I run the plugin these are the themes that mess up for me:
```
[19:52:48] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Starting plugin, Downloading TV Theme Songs...
[19:52:49] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Lockwood & Co. theme song not in database, or no internet connection
[19:52:50] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Scooby-Doo and Guess Who? theme song not in database, or no internet connection
[19:52:51] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The New Scooby and Scrappy-Doo Show theme song not in database, or no internet connection
[19:52:51] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Fate: The Winx Saga theme song not in database, or no internet connection
[19:52:52] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Ice Age: Scrat Tales theme song not in database, or no internet connection
[19:52:53] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Bureau of Magical Things theme song not in database, or no internet connection
[19:52:53] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Zootopia+ theme song not in database, or no internet connection
[19:52:54] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Rock Island Mysteries theme song not in database, or no internet connection
[19:52:55] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Cars on the Road theme song not in database, or no internet connection
[19:52:56] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Lockie Leonard theme song not in database, or no internet connection
[19:52:56] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Soft Border Patrol theme song not in database, or no internet connection
[19:52:57] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Lincoln Lawyer theme song not in database, or no internet connection
[19:52:58] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Completely Made-Up Adventures of Dick Turpin theme song not in database, or no internet connection
[19:52:58] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Shining Vale theme song not in database, or no internet connection
[19:52:59] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: C*A*U*G*H*T theme song not in database, or no internet connection
[19:53:00] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Constellation theme song not in database, or no internet connection
[19:53:01] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Crocodile Hunter: Best of Steve Irwin theme song not in database, or no internet connection
[19:53:02] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Race Against The Tide theme song not in database, or no internet connection
[19:53:03] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Right Stuff theme song not in database, or no internet connection
[19:53:03] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: School of Chocolate theme song not in database, or no internet connection
[19:53:04] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The I-Land theme song not in database, or no internet connection
[19:53:05] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: ted theme song not in database, or no internet connection
[19:53:06] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Population 11 theme song not in database, or no internet connection
[19:53:06] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Manhunt theme song not in database, or no internet connection
[19:53:08] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Love, Death & Robots theme song not in database, or no internet connection
[19:53:08] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Recruit theme song not in database, or no internet connection
[19:53:10] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gogglebox Australia theme song not in database, or no internet connection
[19:53:10] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: A Gentleman in Moscow theme song not in database, or no internet connection
[19:53:11] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gold Rush: Parker's Trail theme song not in database, or no internet connection
[19:53:12] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Dragons' Den theme song not in database, or no internet connection
[19:53:13] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Lost Home Movies of Nazi Germany theme song not in database, or no internet connection
[19:53:13] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Twisted Metal theme song not in database, or no internet connection
[19:53:14] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Tires theme song not in database, or no internet connection
[19:53:15] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Travel Guides theme song not in database, or no internet connection
[19:53:16] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gardening Australia theme song not in database, or no internet connection
[19:53:17] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gold Rush: Dave Turin's Lost Mine theme song not in database, or no internet connection
[19:53:18] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gordon Ramsay on Cocaine theme song not in database, or no internet connection
[19:53:18] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Fat Pizza: Back in Business theme song not in database, or no internet connection
[19:53:19] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Snack vs Chef theme song not in database, or no internet connection
[19:53:20] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Trevor Moore Show theme song not in database, or no internet connection
[19:53:20] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: NCIS: Sydney theme song not in database, or no internet connection
[19:53:21] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Dirty Jobs: Rowe'd Trip theme song not in database, or no internet connection
[19:53:22] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Snackmasters Australia theme song not in database, or no internet connection
[19:53:23] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: BattleBots theme song not in database, or no internet connection
[19:53:24] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gordon Ramsay's 24 Hours to Hell and Back theme song not in database, or no internet connection
[19:53:25] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Bodies theme song not in database, or no internet connection
[19:53:26] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Avatar: The Last Airbender theme song not in database, or no internet connection
[19:53:28] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Tales from the Loop theme song succesfully downloaded
[19:53:28] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Night Agent theme song not in database, or no internet connection
[19:53:29] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Location Scouts theme song not in database, or no internet connection
[19:53:30] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Teenage Bounty Hunters theme song not in database, or no internet connection
[19:53:30] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Fat Pizza Classics theme song not in database, or no internet connection
[19:53:31] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Cockfields theme song not in database, or no internet connection
[19:53:32] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Medical Police theme song not in database, or no internet connection
[19:53:32] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Glitch theme song not in database, or no internet connection
[19:53:34] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Utopia theme song not in database, or no internet connection
[19:53:35] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Santa Clauses theme song not in database, or no internet connection
[19:53:36] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Lovers theme song not in database, or no internet connection
[19:53:36] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Fixer Upper: The Castle theme song not in database, or no internet connection
[19:53:37] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Shark Tank theme song not in database, or no internet connection
[19:53:38] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Dark Matter theme song not in database, or no internet connection
[19:53:39] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Rabbit Hole theme song not in database, or no internet connection
[19:53:40] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gordon Ramsay's Food Stars theme song not in database, or no internet connection
[19:53:41] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Tanked theme song not in database, or no internet connection
[19:53:42] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gold Rush: Mine Rescue with Freddy & Juan theme song not in database, or no internet connection
[19:53:42] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Imagineering Story theme song not in database, or no internet connection
[19:53:43] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Crew theme song not in database, or no internet connection
[19:53:45] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Cleaner theme song not in database, or no internet connection
[19:53:46] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Hell's Kitchen (UK) theme song not in database, or no internet connection
[19:53:46] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Bogan Hunters theme song not in database, or no internet connection
[19:53:47] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Blockbuster theme song not in database, or no internet connection
[19:53:48] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Home Economics theme song not in database, or no internet connection
[19:53:49] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: 3 Body Problem theme song not in database, or no internet connection
[19:53:50] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Mother and Son theme song not in database, or no internet connection
[19:53:51] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Undercover Billionaire theme song not in database, or no internet connection
[19:53:52] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Holey Moley theme song not in database, or no internet connection
[19:53:53] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Hard Quiz theme song not in database, or no internet connection
[19:53:54] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Better Than Us theme song not in database, or no internet connection
[19:53:54] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Gladiators (AU) theme song not in database, or no internet connection
[19:53:55] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: ONE PIECE theme song not in database, or no internet connection
[19:53:55] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: The Crocodile Hunter theme song not in database, or no internet connection
[19:53:56] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Into the Night theme song not in database, or no internet connection
[19:53:57] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Sick Note theme song not in database, or no internet connection
[19:53:57] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Ramsay's Costa del Nightmares theme song not in database, or no internet connection
[19:53:58] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Sugar theme song not in database, or no internet connection
[19:53:59] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Hoffman Family Gold theme song not in database, or no internet connection
[19:54:00] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Goosebumps theme song not in database, or no internet connection
[19:54:01] [INF] [100] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Fallout theme song not in database, or no internet connection
```

If I run a vpn about 10% of those titles aren't there and have the theme song in the folder correctly. Then if I disable my vpn and delete those songs and run again, I get the same songs missing as before. 
This leads me to suspect that there is some sort of georestriction on the source of the theme song. Im guessing maybe its a list of youtube videos or something?
