### ISSUE TITLE
Broken in 10.10

### ISSUE THREAD

**Issue by ashipaek0** [danieladov/jellyfin-plugin-themesongs#38]
Error
Couldn't parse ISO 8601 date string '2024-05-24 20:30:00'

Error: Couldn't parse ISO 8601 date string '2024-05-24 20:30:00'
    at o (https://domain/web/main.jellyfin.bundle.js?a287d3e18cbd61b097f5:2:297893)
    at https://domain/web/plugins-plugin.942f3de331163293b572.chunk.js:1:9626
    at Array.map (<anonymous>)
    at en (https://domain/web/plugins-plugin.942f3de331163293b572.chunk.js:1:9435)
    at hu (https://domain/web/node_modules.react-dom.bundle.js?a287d3e18cbd61b097f5:2:60311)
    at xi (https://domain/web/node_modules.react-dom.bundle.js?a287d3e18cbd61b097f5:2:119252)
    at bs (https://domain/web/node_modules.react-dom.bundle.js?a287d3e18cbd61b097f5:2:108504)
    at vs (https://domain/web/node_modules.react-dom.bundle.js?a287d3e18cbd61b097f5:2:108432)
    at gs (https://domain/web/node_modules.react-dom.bundle.js?a287d3e18cbd61b097f5:2:108295)
    at as (https://domain/web/node_modules.react-dom.bundle.js?a287d3e18cbd61b097f5:2:105130)

**Comment by danieladov** [comment]
Hi there,

I've just released a new version. Could you please check if everything is working as expected now? Let me know if you encounter any issues.

Thank you!
