### ISSUE TITLE
Plugin broken: Unexpected error occured

### ISSUE THREAD

**Issue by jclsn** [danieladov/jellyfin-plugin-themesongs#39]
I installed the .dll from the zip file as the download did also not work as seen here

https://github.com/danieladov/jellyfin-plugin-themesongs/issues/38

After pressing the button, I am getting

```
[2024-10-26 23:51:05.895 +02:00] [INF] [31] Jellyfin.Plugin.ThemeSongs.ThemeSongsManager: Downloading TV Theme Songs
[2024-10-26 23:51:05.898 +02:00] [ERR] [31] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/ThemeSongs/DownloadTVShows".
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<MediaBrowser.Controller.Entities.BaseItem> MediaBrowser.Controller.Entities.BaseItem.GetThemeSongs()'.
   at Jellyfin.Plugin.ThemeSongs.ThemeSongsManager.DownloadAllThemeSongs()
   at Jellyfin.Plugin.ThemeSongs.Api.ThemeSongsController.DownloadTVThemeSongsRequest()
   at lambda_method730(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arg
uments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   ```

**Comment by p37307** [comment]
Also, the catalog page for the plugin  fails to load with this error, which appears to be the date the plugin was released,

```
Error: Couldn't parse ISO 8601 date string '2024-05-24 20:30:00'
    at o (http://library:8096/web/main.jellyfin.bundle.js?f1238435f421c71ad785:2:301722)
    at http://library:8096/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9626
    at Array.map (<anonymous>)
    at en (http://library:8096/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9435)
    at hu (http://library:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:60311)
    at xi (http://library:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:119252)
    at bs (http://library:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108504)
    at vs (http://library:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108432)
    at gs (http://library:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108295)
    at as (http://library:8096/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:105130)
```

**Comment by mikewesten** [comment]
The Plugins Catalog page for all 3 danieladov plugins (Merge Versions, Skin Manager, Theme Songs)
![Screenshot from 2024-10-26 23-19-41](https://github.com/user-attachments/assets/6c2b9107-5cf7-48a4-952b-6f85efe5f37e)

**Comment by S2ciOnur** [comment]
is there any branch or fix planned?

**Comment by p37307** [comment]
> is there any branch or fix planned?

It looks like the dev, @danieladov, fixed the plugin Manifest https://github.com/danieladov/JellyfinPluginManifest/issues/1 a few days ago. That date issue is resolved now. I presume the plugin will get fixed at some point.

**Comment by danieladov** [comment]
Hi there,

I've just released a new version. Could you please check if everything is working as expected now? Let me know if you encounter any issues.

Thank you!

**Comment by jclsn** [comment]
Works for me. Thanks :)

**Comment by p37307** [comment]
Works for me now. Thanks for the fast fix.
