### ISSUE TITLE
Error when i search song

### ISSUE THREAD

**Issue by Killianbe** [danieladov/jellyfin-plugin-themesongs#4]
Hi i've that error when i try search song
can you help me pls  ? 

[22:37:08] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Download Theme Songs

[22:37:08] [INF] [30] Jellyfin.Plugin.ThemeSongs.ScheduledTasks.DownloadThemeSongsTask: Starting plugin, Downloading Theme Songs...

[22:37:08] [ERR] [30] Jellyfin.Plugin.ThemeSongs.ScheduledTasks.DownloadThemeSongsTask: La flamme not found, or no internet connection

System.Net.WebException: The remote server returned an error: (403) Forbidden.

   at System.Net.HttpWebRequest.GetResponse()

   at System.Net.WebClient.GetWebResponse(WebRequest request)

   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)

   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
``

   at System.Net.WebClient.DownloadFile(String address, String fileName)

   at Jellyfin.Plugin.ThemeSongs.ThemeSongsManager.DownloadAllThemeSongs()

[22:37:08] [ERR] [30] Jellyfin.Plugin.ThemeSongs.ScheduledTasks.DownloadThemeSongsTask: Validé not found, or no internet connection

System.Net.WebException: The remote server returned an error: (403) Forbidden.

   at System.Net.HttpWebRequest.GetResponse()

   at System.Net.WebClient.GetWebResponse(WebRequest request)

   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)

   at System.Net.WebClient.DownloadFile(Uri address, String fileName)

   at System.Net.WebClient.DownloadFile(String address, String fileName)

   at Jellyfin.Plugin.ThemeSongs.ThemeSongsManager.DownloadAllThemeSongs()

[22:37:08] [ERR] [30] Jellyfin.Plugin.ThemeSongs.ScheduledTasks.DownloadThemeSongsTask: Emily in Paris not found, or no internet connection

System.Net.WebException: The remote server returned an error: (403) Forbidden.

   at System.Net.HttpWebRequest.GetResponse()

   at System.Net.WebClient.GetWebResponse(WebRequest request)

   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)

   at System.Net.WebClient.DownloadFile(Uri address, String fileName)

   at System.Net.WebClient.DownloadFile(String address, String fileName)

   at Jellyfin.Plugin.ThemeSongs.ThemeSongsManager.DownloadAllThemeSongs()

[22:37:09] [INF] [30] Jellyfin.Plugin.ThemeSongs.ScheduledTasks.DownloadThemeSongsTask: All theme songs downloaded

[22:37:09] [INF] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: Download Theme Songs Completed after 0 minute(s) and 1 seconds

**Comment by danieladov** [comment]
Hi, that error is normal its cause because that tv series is not in Plex database, I'm working to change the plugin so it will download the theme song from youtube if it's not in Plex database
